### ISSUE TITLE
Pictures have white edge under night mode.

### ISSUE THREAD

**Issue by hhao1** [patternize/patternize.io#2]
![Capture](https://user-images.githubusercontent.com/35816566/71740840-2b5c9c00-2e12-11ea-8ce7-486e3ef27b5f.PNG)

**Comment by gazcn007** [comment]
I need to redesign and update the SVGs for these so that they work nicely with both light and dark theme

**Comment by gazcn007** [comment]
This should be fixed by:
https://github.com/patternize/patternize.io/pull/8

as the new icons are in svg instead of png:
![image](https://user-images.githubusercontent.com/12766318/72083542-dc51b380-32b6-11ea-8aee-a0b75d088897.png)
